[package]
name = "luxtensor-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
luxtensor-core = { path = "../core" }

serde = { workspace = true }
tokio = { workspace = true }
libp2p = { workspace = true }
